services:
  app-westiti:
    container_name: app-westiti
    build:
      context: ./App
      dockerfile: dockerfile      
    volumes:
      - ./App:/usr/src/app
      - /usr/src/app/node_modules/
    env_file:
      - .env
    networks:
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-westiti.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app-westiti.entrypoints=web"
      - "traefik.http.services.app-westiti.loadbalancer.server.port=5173"

  api-westiti:
    container_name: api-westiti
    build:
      context: ./Api
      dockerfile: dockerfile
    volumes:
      - ./Api:/usr/src/api
      - /usr/src/api/node_modules/
    env_file:
      - .env    
    networks:
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-westiti.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api-westiti.entrypoints=web"
      - "traefik.http.services.api-westiti.loadbalancer.server.port=3000"

  postgres-westiti:
    container_name: postgres-westiti
    image: postgres:latest
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - westiti
  
  adminer-westiti:
    container_name: adminer-westiti
    image: adminer:latest
    env_file:
      - .env
    networks:      
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer-westiti.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer-westiti.entrypoints=web"
      - "traefik.http.services.adminer-westiti.loadbalancer.server.port=8080" 

  traefik-westiti:
    container_name: traefik-westiti
    image: traefik:latest
    ports:
      - "80:80"
      - "8081:8080"
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-westiti.entrypoints=web"
      - "traefik.http.routers.traefik-westiti.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-westiti.service=api@internal"
    env_file:
      - .env
networks:
  westiti:
    driver: bridge