FROM node:20

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
WORKDIR /usr/src/api

COPY package*.json ./
# RUN apk update && apk add openssl

# RUN npm install
RUN npm ci --only=development

COPY . .

# RUN npm run build

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]